---

- name: Set Git Directory Default
  set_fact:
    repo_path: "{{ ansible_env.HOME }}/{{ kr_repo_path }}"
  when: kr_repo_path.find("home") == -1

- name: Set Git Directory Custom
  set_fact:
    repo_path: "{{ kr_repo_path }}"
  when: kr_repo_path.find("home") != -1

- name: Clean Up Artifacts
  shell:
    chdir: "{{ repo_path }}"
    cmd: make clean
  when: clean is defined

- name: Run Lint & Tests (optional)
  shell:
    chdir: "{{ repo_path }}"
    cmd: make gofmt lint test
  when: testing is defined

- name: Find Git Version
  shell:
    chdir: "{{ repo_path }}"
    cmd: git describe --tags --abbrev=0
  register: git_commit

- name: Set Build Date
  command: date +%Y-%m-%dT%H:%M:%S%z
  register: build_date

- name: Build kube-router
  shell:
    chdir: "{{ repo_path }}"
    cmd: >
      CGO_ENABLED=0 {{ go_ver | default("go", true) }} build -gcflags="all=-N -l" -ldflags
      "-X github.com/cloudnativelabs/kube-router/v2/pkg/version.Version={{ git_commit.stdout }}
      -X github.com/cloudnativelabs/kube-router/v2/pkg/version.BuildDate={{ build_date.stdout }}"
      -o kube-router cmd/kube-router/kube-router.go
