---

- name: Set Git Directory Default
  set_fact:
    repo_path: "{{ ansible_env.HOME }}/{{ kr_repo_path }}"
  when: kr_repo_path.find("home") == -1

- name: Set Git Directory Custom
  set_fact:
    repo_path: "{{ kr_repo_path }}"
  when: kr_repo_path.find("home") != -1

- name: Cleanup Local .tar File
  file:
    path: "{{ repo_path }}/kube-router.tar"
    state: absent

- name: Cleanup Container Now That It's Been Exported
  shell:
    cmd: docker rmi {{ container_name }}
