---

- name: Set Git Directory Default
  set_fact:
    repo_path: "{{ ansible_env.HOME }}/{{ kr_repo_path }}"
  when: kr_repo_path.find("home") == -1

- name: Set Git Directory Custom
  set_fact:
    repo_path: "{{ kr_repo_path }}"
  when: kr_repo_path.find("home") != -1

- name: Create Container
  shell:
    chdir: "{{ repo_path }}"
    cmd: make container
  register: container_build_out

- name: Find Container Name
  set_fact:
    container_name:
      "{{ container_build_out.stderr | regex_search('naming to ([^ ]+)', '\\1') | first }}"

- name: Container Name from Build
  debug:
    msg: 'Found container name: {{ container_name }}'

- name: Create Unique Tag
  set_fact:
    unique_container_name: "{{ container_name }}-{{ 999999 | random | to_uuid }}"

- name: Unique Container Name
  debug:
    msg: 'Found container name: {{ unique_container_name }}'

- name: Make Container Tag Unique
  shell:
    cmd: docker tag {{ container_name }} {{ unique_container_name }}

- name: Export Container
  shell:
    chdir: "{{ repo_path }}"
    cmd: docker save -o kube-router.tar {{ unique_container_name }}
