---

- name: Find UID
  become: no
  command: id -u
  register: user_id

- name: Find GID
  become: no
  command: id -g
  register: group_id

- name: Find Home
  become: no
  command: echo ${HOME}
  register: home

- name: Output UID & GID
  debug:
    msg: "User ID: {{ user_id.stdout }} / Group ID: {{ group_id.stdout }}"

- name: Create kube Config Dir in User's Home
  file:
    path: "{{ home.stdout }}/.kube"
    state: directory
    mode: '0750'
    owner: "{{ user_id.stdout }}"
    group: "{{ group_id.stdout }}"

- name: Grab Kube Config from Leader
  slurp:
    src: /etc/kubernetes/admin.conf
  delegate_to: "{{ item }}"
  register: kube_config
  loop: "{{ groups['leader'] }}"

- name: Copy Kube Config to Home
  copy:
    # Because we used a loop command (even over just one host) we have to parse results to get to stdout
    content: "{{ kube_config['results'][0]['content'] | b64decode }}"
    dest: "{{ home.stdout }}/.kube/config"
    mode: '0600'
    owner: "{{ user_id.stdout }}"
    group: "{{ group_id.stdout }}"