---

- name: Find UID
  become: no
  command: id -u
  register: user_id

- name: Find GID
  become: no
  command: id -g
  register: group_id

- name: Find Home
  become: no
  command: echo ${HOME}
  register: home

- name: Output UID & GID
  debug:
    msg: "User ID: {{ user_id.stdout }} / Group ID: {{ group_id.stdout }}"

- name: Create kube Config Dir in User's Home
  become: no
  file:
    path: "{{ home.stdout }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ user_id.stdout }}"
    group: "{{ group_id.stdout }}"

- name: Copy Kube Config to Home
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "{{ home.stdout }}/.kube/config"
    mode: '0700'
    owner: "{{ user_id.stdout }}"
    group: "{{ group_id.stdout }}"