---

- name: Add Kubernetes Repo Key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
    state: present

- name: Add Kubernetes Repository
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
    state: present
    filename: kubernetes

- name: Install Kubernetes Components
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes

- name: Probe br_netfilter Modules
  command: modprobe br_netfilter

- name: Ensure br_netfilter Probe Runs on Startup
  copy:
    content: "br_netfilter"
    dest: "/etc/modules-load.d/kubernetes.conf"
    mode: '0755'
