---
- name: Find User Identity
  become: false
  shell: echo "$(id -u) $(id -g) ${HOME}"
  register: user_ident
  changed_when: false

- name: Set User Identity Facts
  set_fact:
    user_id: "{{ user_ident.stdout.split()[0] }}"
    group_id: "{{ user_ident.stdout.split()[1] }}"
    home: "{{ user_ident.stdout.split()[2] }}"

- name: Find Remote Home
  become: false
  command: echo ${HOME}
  register: remote_home
  delegate_to: "{{ item }}"
  loop: "{{ groups['leader'] }}"

- name: Output UID & GID
  debug:
    msg: "User ID: {{ user_id }} / Group ID: {{ group_id }}"

- name: Create kube Config Dir in User's Home
  file:
    path: "{{ home }}/.kube"
    state: directory
    mode: "0750"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"

- name: Grab kube config from Leader
  slurp:
    src: "{{ remote_home.results[0].stdout }}/.kube/config"
  delegate_to: "{{ item }}"
  register: kube_config
  loop: "{{ groups['leader'] }}"

- name: Check if local kube/config exists locally
  stat:
    path: "{{ home }}/.kube/config"
  register: local_config_path

- name: Backup existing kubeconfig
  copy:
    src: "{{ home }}/.kube/config"
    dest: "{{ home }}/.kube/config.bak"
    mode: "0600"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
  when: local_config_path.stat.exists

- name: Copy Kube Config to Home
  copy:
    # Because we used a loop command (even over just one host) we have to parse results to get to stdout
    content: "{{ kube_config['results'][0]['content'] | b64decode }}"
    dest: "{{ home }}/.kube/config"
    mode: "0600"
    owner: "{{ user_id }}"
    group: "{{ group_id }}"

- name: Replace internal IP with external IP
  replace:
    path: "{{ home }}/.kube/config"
    regexp: '{{ hostvars["aws-controller"].ansible_facts["default_ipv4"].address }}'
    replace: '{{ hostvars["aws-controller"].ec2_public_ip if hostvars["aws-controller"].get("ec2_public_ip", "") != "" else hostvars["aws-controller"].ansible_host }}'
  when: hostvars["aws-controller"] is defined
