---

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install containerd.io
  apt:
    name: containerd.io
    update_cache: true

- name: Create containerd Config Dir
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Generate containerd Config
  shell: containerd config default | sed -r 's/(SystemdCgroup = )false/\1true/g'
  register: containerd_config

- name: Write containerd Config
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: '0755'

- name: Create containerd kubelet Config Dir
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Write containerd Kubelet Config
  template:
    src: templates/kubernetes-containerd.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/0-containerd.conf

- name: Start / Enable containerd Service
  systemd:
    name: containerd
    enabled: true
    state: restarted
    daemon_reload: true
