---

- name: Add Docker GPG apt Key (apt)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Add Docker Repository (apt)
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_pkg_mgr == "apt"

- name: Install dnf-plugins-core (dnf)
  dnf:
    name: dnf-plugins-core
  when: ansible_pkg_mgr == "dnf"

- name: Install docker containerd repos (dnf)
  command: dnf-3 config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_pkg_mgr == "dnf"

- name: Install containerd.io (apt)
  apt:
    name: containerd.io
    update_cache: true
  when: ansible_pkg_mgr == "apt"

- name: Install containerd.io (dnf)
  dnf:
    name: containerd.io
    update_cache: true
  when: ansible_pkg_mgr == "dnf"

- name: Create containerd Config Dir
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Generate containerd Config
  shell: containerd config default | sed -r 's/(SystemdCgroup = )false/\1true/g'
  register: containerd_config

- name: Write containerd Config
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: '0755'

- name: Start / Enable containerd Service
  systemd_service:
    name: containerd
    enabled: true
    state: restarted
    daemon_reload: true

- name: Get Latest nerdctl Tarball Version
  uri:
    url: "https://api.github.com/repos/containerd/nerdctl/releases/latest"
    return_content: true
  register: json_response

- name: Parse Latest Nerdctl Tarball Version
  set_fact:
    amd64_nerdctl: "{{ json_response | community.general.json_query(download_query) }}"
  vars:
    download_query: "json.assets[?contains(name, 'linux-amd64') && !contains(name, 'full')].browser_download_url"

# - name: Show Download URL
#  debug:
#    msg: "nerdctl Download URL: {{amd64_nerdctl[0]}}"

- name: Grab nerdctl Binary
  unarchive:
    src: "{{ amd64_nerdctl[0] }}"
    dest: /usr/local/bin
    remote_src: true
    include:
      - nerdctl
