---

# cloudinit / libvirt Terraform don't seem to set an acceptable hostname value and leave it as ubuntu. So let's set it
- name: Set a Hostname
  hostname:
    name: "{{ inventory_hostname }}"

# We have some pending sysctl changes that need to be enacted on all systems
- name: Update sysctl
  command: sysctl --system

- name: Install Standard Network Utils (apt)
  apt:
    name:
      - iputils-ping
      - dnsutils
      - tcpdump
      - iperf3
      - ndisc6
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 20
  when: ansible_pkg_mgr == "apt"

- name: Install Standard Network Utils (dnf)
  dnf:
    name:
      - iputils
      - dnsutils
      - tcpdump
      - iperf3
      # This isn't available in rocky linux - ndisc6
    update_cache: true
  register: dnf_status
  until: dnf_status is success
  delay: 6
  retries: 20
  when: ansible_pkg_mgr == "dnf"
