---

# cloudinit / libvirt Terraform don't seem to set an acceptable hostname value and leave it as ubuntu. So let's set it
- name: Set a Hostname
  hostname:
    name: "{{ inventory_hostname }}"

# We have some pending sysctl changes that need to be enacted on all systems
- name: Update sysctl
  command: sysctl --system

- name: Install Standard Network Utils
  apt:
    name:
      - iputils-ping
      - dnsutils
      - tcpdump
      - iperf3
      - ndisc6
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 20
