all:
  hosts:
    kube-router-vm1:
    kube-router-vm2:
    bgp-route-vm1:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Only the libvirt inventory needs to become root on localhost to apply NAT/forwarding rules
    # for VM traffic, so we use this to skip that play entirely for AWS inventory hosts.
    libvirt_deployment: true
  children:
    container_runners:
      hosts:
        kube-router-vm1:
        kube-router-vm2:
    controllers:
      hosts:
        kube-router-vm1:
    leader:
      hosts:
        kube-router-vm1:
    workers:
      hosts:
        kube-router-vm2:
    bgp_routers:
      hosts:
        bgp-route-vm1: