- name: Setup Base Packages
  hosts: container_runners
  become: yes
  tags:
    - setup
  tasks:
    - name: Setup & Run Containerd
      import_role:
        name: container_runner
        tasks_from: setup_containerd.yaml
    - name: Setup Kubernetes
      import_role:
        name: kubernetes
        tasks_from: install_kubernetes.yaml

- name: Create Cluster
  hosts: leaders
  become: yes
  tasks:
    - name: Create Cluster with kubeadm
      tags:
        - cluster
      import_role:
        name: kubernetes
        tasks_from: initialize_cluster.yaml
        vars_from: containerd
    - name: Setup User Kube Config
      tags:
        - user_config
      import_role:
        name: kubernetes
        tasks_from: copy_kubeconfig.yaml