- name: Setup Base Packages
  hosts: container_runners
  become: yes
  tags:
    - setup
  tasks:
    - name: Setup & Run Containerd
      import_role:
        name: container_runner
        tasks_from: setup_containerd
    - name: Setup Kubernetes
      import_role:
        name: kubernetes
        tasks_from: install_kubernetes

- name: Create Cluster
  hosts: leader
  become: yes
  tasks:
    - name: Create Cluster with kubeadm
      tags:
        - cluster
        - leader
      import_role:
        name: kubernetes
        tasks_from: initialize_cluster
        vars_from: containerd
    - name: Setup User Kube Config
      tags:
        - user_config
      import_role:
        name: kubernetes
        tasks_from: copy_kubeconfig

- name: Join Cluster with Remaining Nodes
  hosts: workers
  become: yes
  serial: 1
  tasks:
    - name: Join Cluster with kubeadm
      tags:
        - cluster
        - workers
      import_role:
        name: kubernetes
        tasks_from: join_cluster
        vars_from: containerd
    - name: Setup User Kube Config
      tags:
        - user_config
      import_role:
        name: kubernetes
        tasks_from: copy_kubeconfig