---
# For just having some kube-router features along with kube-proxy
# manifest: https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml

# For having all features of kube-router enabled
manifest: "https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter-all-features.yaml"
kube_router_docker_repo: docker.io/cloudnativelabs/kube-router
kube_router_version: latest
